Added the possibility to define the order of an export.
hyperdevs-team/poeditor-android-gradle-plugin pull request #58
Opened 2022-10-19 12:21 UTC by WarrenFaith

### PR's key points
Added support to configure an order for the export.
 
### How to review this PR?
Carefully please, I have never worked on a plugin project before. I am also not sure if there would be a meaningful test to be written.
 
### Definition of Done
- [ x] Changes summary added to CHANGELOG.md
- [ x] Documentation added to README.md (if a new feature is added)
- [ ] Tests added (if new code is added)
- [ x] There is no outcommented or debug code left

PS: would be cool to have this supported for the swift/iOS version too, but I am not capable of doing that...

2022-11-13 19:06 UTC, adriangl requested changes
Hello! Sorry for the late reply, and thanks for the contribution!

Please review the changes I requested, they are mostly style and syntax suggestions, the code overall looks good apart from these changes.

2022-11-13 19:06 UTC, adriangl commented on src/main/kotlin/com/hyperdevs/poeditor/gradle/Main.kt
> +    val order = dotenv.get("ORDER", "terms")
If you apply the suggestions I made, I'd set the value to `none`

2022-11-13 19:06 UTC, adriangl commented on src/main/kotlin/com/hyperdevs/poeditor/gradle/PoEditorStringsImporter.kt
> +                              order: String?,
If you apply the suggested changes, then make this a `String` value

2022-11-13 19:06 UTC, adriangl commented on src/main/kotlin/com/hyperdevs/poeditor/gradle/network/PoEditorApiController.kt
> +            order = order,
If you use the enum approach, I would do something like this so we can pass the `NONE` value as null to the API:
```
            order = order.takeIf { it != OrderType.NONE }?.toLowerCase(), 
```

2022-11-15 11:14 UTC, WarrenFaith commented
Hey, thanks for the feedback. I rebased to latest master and took the FilterType as a guidance.
Let me know if there is still something I should change.

2022-11-16 13:58 UTC, merged